version = '2'

[formatters]
enable = ['gofmt']

[formatters.exclusions]
generated = 'lax'
paths = ['third_party$', 'builtin$', 'examples$']

[linters]
enable = ['revive', 'misspell', 'bodyclose']

[linters.exclusions]
generated = 'lax'
paths = ['third_party$', 'builtin$', 'examples$']

[[linters.exclusions.rules]]
linters = ['revive']
path = '(.+)_test\.go'
text = 'dot-imports:'

[run]
timeout = '15m'
