name: coverage report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    name: generate and publish coverage
    env:
      COVERAGE_REPORT: coverage.txt

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: generate coverage report
        run: make coverage

      - name: upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          directory: .
          files: ${{env.COVERAGE_REPORT}}
          flags: tests
          name: codecov-umbrella
          verbose: true
