name: terrastack-ci
on: [push]
jobs:

  lint:
    runs-on: ubuntu-20.04

    # Lint with all supported go versions
    # Doesn't seem necessary to lint on different OS's
    strategy:
      matrix:
        go: ["1.17"]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: make lint
        run: make lint

  build_test:
    name: Build and Test

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-2019]
        go: ["1.17"]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: make test
        run: time make test

      - name: make build
        run: make build
